language: android

sudo: required

env:
  global:
  - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=512m -XX:PermSize=512m"
  - secure: kj+d9zNAgYgWxT+nC6A17coMnM62bl24zaKpf1v24uoYYrO3Wj13g1ltQoAk5oXm9EZ378pOk+gzPNxIdop8HsOd+7RTHCLiG6z+HOwOY3EQ88+KbjSRJ3O1wZ0GYu/DheL/q1JQwliEwstICdl5R05+4nlOxByqGb0msbrdgsymKI8GyIv5+yL7ieYe3YNn58JxDcIGKMVwfX7McK0FQ/OLBza0NJPIEE62ptGXvLsdA8P9YeTzpMNoUuzM3Lql8lD9qDZd0E8WanJIYMWB0Ck8ddTVEKAShfLvLZ7qlrmqbXa+4qc9FXqW3HhY2yeVJd5sQGlnVmq5vaRyz9CLdGvqZ6IqXMoDoApez1yPx55EwHHAg2D5GzkWezFpOGW4PJ6WOljRYkbHFRFLOH+SWlMy6TX6XXYc43xZU52fOxYmCV50ef0iF3UgB0Iq2106Qz0xiDJ4shlDLyn3ZJScOgl3OfWef+AkIIIsDu//Bun0mxrFdxk/mmqpMSivVpXyc8+mrlPyJgakP74E5L971WgBQ3dSTnJy5YPPtPSKxV5yWtd2H76cKQkfKr5tIJU5svFu3Ubh1WQvQQRewVGGQmAyx3iTpZ5ahtfihLk61CqYmReDZZFhy6CTcDl1XWqsVXieMQ1PVNSBCnkSeZUsTtzEz3pU2r112SBEyFuwzn8=

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-23

script:
  ./gradlew :flux-framework:build :flux-processor:build test

notifications:
  slack:
    secure: e7Tl/jc7e/6LUclFTDeHcnLZLgM2pTqEFqQG+fI6sEaKaE61L6kG/Z9xgfmIGrb9A0f1W/Di7MF6wFs20/+aB4q58m0E6cRLIm4c7mhqN0rkVWOyqa6ssf9cYAKHoK9Nqsh+nbdqtWimJkuu9HP2rPnnlzsentWo8imcnoumQAopDbs1LrmNKwwjFVniusuwxLzxtDEFFtZvAl6R0NA86YLwGNY1BsuoWxijw7P+KceCO60IWJVeU6Wg568N5X67JsA59lmFTKRHqYF+6L9BiuaBKJbqjsLqzU8kc7lQjJlZ634XKIq8UEtmmjrYi97Wxt9EDdKeZSr76qMdeblaURpuSaBzODEywUVqSIL44IPHgl+L8rwhdItSc+xkzZk22TNgbW0TagSNaonLF3EQ9bgH5FFs1vmShZFHy1GyTEpo73SKZ3DpmLz+xERAcnkZgiNEQWROZwV0pc8OX+f1xx7oXB5g/5eIvHLqaZ3ar9WguovikV+dHFnG3he6zxPI/riWbBsV2ODZ0yFpRl+hT+pJISm1ap4cHMtH6T+Rp4nue6NYvaBVvZXeDGZvlp2NXxYe6iH0jCGxte0bIZGt4tp0Ba7KOTBsB+T7iXior6DmKybD15ImPxhEbRnqVWqaXXcggTYpkpvaxniNHVJPEX6ARbIuQaETaZYxGJKH9U8=

after_success:
  - ./upload_bintray.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
