language: android

sudo: required

env:
  global:
  - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=512m -XX:PermSize=512m"
  - secure: w9HbC5E9C8EG5aFPSPVav3n3Mzwl9ljla4l8eM39wvJjaM4UryAviL8dOdE9o+T2cjGSZYXmFQSvQ1Ld+Qgj4VVxJufWW0jvD/I4y9XeuzQgD4HMD1hPLcvD1+C1bOijvvWVEmQs8Ew6lj+tQfio8DNCAmzWdy19kIt1lLGx0lnLDR6eVrHW9+N6k+rHjzixWLTZunR+F+LX2MCwCbf2av6b5SmvhpUJeB7HkA3TpJTfllVl7w2zc5Lk1glSAH9fJVSYkdfQw/2BdISUF2abgREGh6142qtdmwXY05qqLTFANj7ixPAQlWX2vytEv6AFn+EVCsbI2rBpFwqocn4Piucl8eM8uzTjTlpPJeASW1Tgw1pcJh4f8CpXw4Rxzn0/T6S4ZwvOUk3GL3nar1RJ47PzeoQlIi5Tmb0nk5kfjJMBYIxSKc5g2SGaoisAZ06GGhyPWso59mEf6q8/g2zUI8fRNtnEfxGGd96vKCGlmkfMwKgQ5aUp+cLRmLCppT5++V19qt2+mZEpMIjebcIrvZdTfIqZ92DpzmtqiI89VOfyRscRjT0ZQ8gKzgkQ21oNTJBmLD8R2tj4rRCiipiYdrz+wx2SVN5AmXviXWHH1LYHkbIvElwyaWOjipejyXUEaVitm476NQSiRWboJEj1Gq2nshvJMpexe7M3/cN9LqI=

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-25

script:
  ./gradlew :flux-framework:build :flux-processor:build :flux-framework-kotlin:build :flux-utility-kotlin:build test

notifications:
  slack:
    secure: e7Tl/jc7e/6LUclFTDeHcnLZLgM2pTqEFqQG+fI6sEaKaE61L6kG/Z9xgfmIGrb9A0f1W/Di7MF6wFs20/+aB4q58m0E6cRLIm4c7mhqN0rkVWOyqa6ssf9cYAKHoK9Nqsh+nbdqtWimJkuu9HP2rPnnlzsentWo8imcnoumQAopDbs1LrmNKwwjFVniusuwxLzxtDEFFtZvAl6R0NA86YLwGNY1BsuoWxijw7P+KceCO60IWJVeU6Wg568N5X67JsA59lmFTKRHqYF+6L9BiuaBKJbqjsLqzU8kc7lQjJlZ634XKIq8UEtmmjrYi97Wxt9EDdKeZSr76qMdeblaURpuSaBzODEywUVqSIL44IPHgl+L8rwhdItSc+xkzZk22TNgbW0TagSNaonLF3EQ9bgH5FFs1vmShZFHy1GyTEpo73SKZ3DpmLz+xERAcnkZgiNEQWROZwV0pc8OX+f1xx7oXB5g/5eIvHLqaZ3ar9WguovikV+dHFnG3he6zxPI/riWbBsV2ODZ0yFpRl+hT+pJISm1ap4cHMtH6T+Rp4nue6NYvaBVvZXeDGZvlp2NXxYe6iH0jCGxte0bIZGt4tp0Ba7KOTBsB+T7iXior6DmKybD15ImPxhEbRnqVWqaXXcggTYpkpvaxniNHVJPEX6ARbIuQaETaZYxGJKH9U8=

after_success:
  - ./upload_bintray.sh
  - ./gradlew jacocoTestReport coveralls

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
