language: android

sudo: required

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-23

script:
  ./gradlew :flux-processor:test

