language: android

sudo: required

env:
  global:
  - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=512m -XX:PermSize=512m"
  - secure: DoCyTbcxkfbdIF/YWJoI9rZZ+zGHEBoHgzS9U98z4xHEjWtVh4Wuo1zlEuNfbEWoOgnuPeEGWy6M/9kP0ey8A79jqMG1MrGkOcq5RdcqXhEm5qDCmf4y51Sqqj/MbLCLod3UjFR4A2cc1GxLCFMoMXG6Uz/mXjA/3Bt7j4PYhKvNkPe5nn1aibroVfAJwMVbn9QfkJscLO3EPw1rbveI47KNTc6IiURJSAjS9mstYl0NVdEj4T40p+fIpXF8RmMkwuqHvqs7JA+TbYrId2cqORqb3xbXQBHZ2hWJVvkmvfcm2kUb+5gHnA3ylU8eHFwaM43tJSjpm3gJ2tUU94eUUZQWcgJpEcXMETcK5gfessFe4gWoZ1gHOWKSdGprEWdhMKFJLSzP9XJwfDYUEft4IZnKnuAGg920PLbQVy9uc2AnT1YmcccKN3tQZoT8RndIKSl6K0sXsxApr8mIbVcIuHxiUxH6ZCXly1fdHPziABt4bjmYoeP9UohfiIX1kFkqPR9FaMRMn8FyRQmPz7sSvOla9525Gy7Zz3JHAgossISm9zUmBRhP3FqTJL6+Uo9j5cOs1KSXlOLJYZGQ0Z8tBc9CQWiCYJ/jC/GaBAhFI5H9IetcMH0Yq3AyTici/fjdGKBPiY0XhPNOQTI6HlWVQ2d/hx4hBUNePb1U9ifQbSA=

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-23

script:
  ./gradlew :flux-framework:build :flux-processor:build test

notifications:
  slack:
    secure: e7Tl/jc7e/6LUclFTDeHcnLZLgM2pTqEFqQG+fI6sEaKaE61L6kG/Z9xgfmIGrb9A0f1W/Di7MF6wFs20/+aB4q58m0E6cRLIm4c7mhqN0rkVWOyqa6ssf9cYAKHoK9Nqsh+nbdqtWimJkuu9HP2rPnnlzsentWo8imcnoumQAopDbs1LrmNKwwjFVniusuwxLzxtDEFFtZvAl6R0NA86YLwGNY1BsuoWxijw7P+KceCO60IWJVeU6Wg568N5X67JsA59lmFTKRHqYF+6L9BiuaBKJbqjsLqzU8kc7lQjJlZ634XKIq8UEtmmjrYi97Wxt9EDdKeZSr76qMdeblaURpuSaBzODEywUVqSIL44IPHgl+L8rwhdItSc+xkzZk22TNgbW0TagSNaonLF3EQ9bgH5FFs1vmShZFHy1GyTEpo73SKZ3DpmLz+xERAcnkZgiNEQWROZwV0pc8OX+f1xx7oXB5g/5eIvHLqaZ3ar9WguovikV+dHFnG3he6zxPI/riWbBsV2ODZ0yFpRl+hT+pJISm1ap4cHMtH6T+Rp4nue6NYvaBVvZXeDGZvlp2NXxYe6iH0jCGxte0bIZGt4tp0Ba7KOTBsB+T7iXior6DmKybD15ImPxhEbRnqVWqaXXcggTYpkpvaxniNHVJPEX6ARbIuQaETaZYxGJKH9U8=

after_success:
  - ./upload_bintray.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
